
services:
  api:
    build:
        dockerfile: docker/api/Dockerfile
        context: .

  nginx:
    build:
        dockerfile: docker/nginx/Dockerfile
        context: .
    ports:
      - "127.0.0.1:${APP_PORT?must be defined}:80"
